services:
  vpnserver:
    build:
      context: ./vpnserver
    cap_add:
      - NET_ADMIN  # Allow network administration capabilities
      - SYS_MODULE  # Allow loading kernel modules
    networks:
      vpn_network:
      servers_network:
        ipv4_address: 192.168.1.10   # Additional IP in the internal network

  webserver:
    build:
      context: ./webserver
    networks:
      servers_network:
        ipv4_address: 192.168.1.20   # Web server internal IP

  nginx:
    image: nginx:latest
    volumes:
      - nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  # Expose port 80 for Nginx
    networks:
      servers_network:
        ipv4_address: 192.168.1.30   # Nginx internal IP

networks:
  vpn_network:
    driver: overlay  
    external: true
           

  servers_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24      # Subnet for internal servers
