services:
  vpnserver:
    build:
      context: ./vpnserver
    networks:
      vpn_network:
        ipv4_address: 10.0.0.1

  webserver:
    build:
      context: ./webserver
    networks:
      vpn_network:
        ipv4_address: 192.168.1.20

networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
