services:
  vpnserver:
    build:
      context: ./vpnserver
    cap_add:
      - NET_ADMIN  # Allow network administration capabilities
      - SYS_MODULE  # Allow loading kernel modules
    networks:
      vpn_network:
      servers_network:
              ipv4_address: 192.168.1.20   # VPN internal IP

  webserver:
    build:
      context: ./webserver
    networks:
      servers_network:


networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24         # Subnet for VPN connections

  servers_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24      # Subnet for internal servers
