version: '3.8'

services:
  strongswan:
    build: ./strongswan
    cap_add:
      - NET_ADMIN
    networks:
      vpn_net:
        ipv4_address: 192.168.1.10  # StrongSwan container IP
    restart: always

  webserver:
    build: ./webserver
    networks:
      vpn_net:
        ipv4_address: 192.168.1.20  # Web server container IP
    ports:
      - "5000:5000"  # Expose the web server port
    restart: always

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
