services:
  client:
    build:
      context: .
    cap_add:
      - NET_ADMIN  # Allow network administration capabilities
      - SYS_MODULE  # Allow loading kernel modules
    networks:
      vpn_network:

networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
